const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('settingsAPI', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.send('save-settings', settings),
  registerShortcut: (type, shortcut) => ipcRenderer.invoke('register-shortcut', { type, shortcut }),
  checkShortcutConflict: (shortcut) => ipcRenderer.invoke('check-shortcut-conflict', shortcut),
  restoreDefaults: () => ipcRenderer.invoke('restore-defaults'),
  onSettingsChanged: (callback) => ipcRenderer.on('settings-changed', (_event, settings) => callback(settings)),
  getApps: () => ipcRenderer.invoke('get-apps'),
  overrideAppIcon: (appId, exePath) => ipcRenderer.invoke('override-app-icon', { appId, exePath }),
  resetAppIcon: (appId, exePath) => ipcRenderer.invoke('reset-app-icon', { appId, exePath }),
  onAppsUpdated: (callback) => ipcRenderer.on('apps-updated', () => callback()),
  getDockConfig: () => ipcRenderer.invoke('get-config'),
  readRawConfig: () => ipcRenderer.invoke('read-raw-config'),
  writeRawConfig: (content) => ipcRenderer.invoke('write-raw-config', content),
  setPinnedAppExec: (appId, exec) => ipcRenderer.invoke('set-pinned-app-exec', { appId, exec }),
  setDockAppIcon: (appId) => ipcRenderer.invoke('set-dock-app-icon', { appId }),
  resetDockAppIcon: (appId) => ipcRenderer.invoke('reset-dock-app-icon', appId),
  setDockIconSize: (size) => ipcRenderer.invoke('set-dock-icon-size', size),
  onConfigUpdated: (callback) => ipcRenderer.on('config-updated', (_event, config) => callback(config)),
  saveAutoHide: (autoHide) => ipcRenderer.send('save-auto-hide', autoHide),
  saveDockHidingMode: (mode) => ipcRenderer.send('save-dock-hiding-mode', mode),
  getHideSettings: (target) => ipcRenderer.invoke('get-hide-settings', target),
  saveHideSettings: (payload) => ipcRenderer.send('save-hide-settings', payload),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  exportTheme: (name) => ipcRenderer.invoke('export-theme', name),
  importTheme: () => ipcRenderer.invoke('import-theme'),
  applyBuiltinTheme: (name) => ipcRenderer.invoke('apply-builtin-theme', name),
  revertLastImport: () => ipcRenderer.invoke('revert-last-import'),
  pressEscape: () => ipcRenderer.send('escape-pressed'),
  onThemeChanged: (callback) => ipcRenderer.on('theme-changed', (_event, data) => callback(data)),
  getThemeConfig: () => ipcRenderer.invoke('get-theme-config'),
  getDisplays: () => ipcRenderer.invoke('get-displays'),
  getRamUsage: () => ipcRenderer.invoke('get-ram-usage'),
  clearIconCache: () => ipcRenderer.invoke('clear-icon-cache'),
  refreshApp: () => ipcRenderer.send('refresh-app'),
  openErrorLog: () => ipcRenderer.send('open-error-log'),
  openConfigFolder: () => ipcRenderer.invoke('open-config-folder'),
  readExperimentalFlags: () => ipcRenderer.invoke('read-experimental-flags'),
  saveExperimentalFlags: (flags) => ipcRenderer.invoke('save-experimental-flags', flags),
  readRawSettings: () => ipcRenderer.invoke('read-raw-settings'),
  writeRawSettings: (content) => ipcRenderer.invoke('write-raw-settings', content),
  getDebugInfo: () => ipcRenderer.invoke('get-debug-info'),
  setVerboseLogging: (enabled) => ipcRenderer.send('set-verbose-logging', enabled),
  getWidgetActiveSummary: () => ipcRenderer.invoke('get-widget-active-summary'),
  onNotificationChanged: (callback) => ipcRenderer.on('notification-settings-changed', (_event, data) => callback(data)),
  taskbarGetState: () => ipcRenderer.invoke('taskbar-get-state'),
  taskbarHide: () => ipcRenderer.invoke('taskbar-hide'),
  taskbarShow: () => ipcRenderer.invoke('taskbar-show'),
  taskbarWriteRestoreScript: () => ipcRenderer.invoke('taskbar-write-restore-script'),
  forceResetUI: () => ipcRenderer.invoke('force-reset-ui'),
  previewTheme: (tempAppearance) => ipcRenderer.send('preview-theme', tempAppearance),
  getCrashReports: () => ipcRenderer.invoke('get-crash-reports'),
  clearCrashReports: () => ipcRenderer.invoke('clear-crash-reports'),
  runHealthCheck: () => ipcRenderer.invoke('run-health-check'),
  replayOnboarding: () => ipcRenderer.invoke('replay-onboarding'),
  testDockHide: () => ipcRenderer.send('test-dock-hide'),
  testMenuBarHide: () => ipcRenderer.send('test-menubar-hide')
});
